name: Deploy to Vercel 

env:
  KOPI_TOKEN: ${{ secrets.KOPI_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Periksa repositori
        uses: actions/checkout@v2

      - name: Pasang Project CLI
        run: npm install --global vercel@latest

      - name: Pasang dependencies
        run: npm install --frozen-lockfile

      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Bangun app
        run: npm run build

      - name: Tarik Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.KOPI_TOKEN }}

      - name: Bangun Project Artifacts
        run: vercel build --prod --token=${{ secrets.KOPI_TOKEN }}
        
      - name: Unggah Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.KOPI_TOKEN }}